In [11]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

Docstring shortcut 'Shift + Tab'

In [2]:
odd_number_list = [1, 3, 5, 7]

In [6]:
np.array(odd_number_list)

array([1, 3, 5, 7])

In [7]:
two_dim_list = ([1, 1, 1], [2, 2, 2], [3, 3, 3])
np.array(two_dim_list)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [25]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(3)

array([0.58068559, 0.80290894, 0.01213812])

In [30]:
np.random.rand(3, 4)

array([[0.20627496, 0.81726885, 0.67297772, 0.46394089],
       [0.96502786, 0.70754195, 0.62702189, 0.42114268],
       [0.57141404, 0.60192634, 0.69725236, 0.60814098]])

In [31]:
np.random.randn(3)

array([-1.71923968, -0.32980268,  0.11948501])

In [33]:
np.random.randint(0, 50, 20)

array([37, 40,  5, 42, 47, 44, 29, 10, 35, 42,  0, 13, 14, 11,  6, 31,  7,
       24, 38, 27])

In [34]:
rand_arr = np.random.randint(0, 50, 20)

In [35]:
rand_arr

array([18,  8, 24,  0, 48, 32, 16, 49,  9, 18, 25, 13, 13, 41,  5,  0, 12,
       31, 24, 18])

In [36]:
second_arr = np.arange(20)

In [37]:
second_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
rand_arr.reshape(4, 5)

array([[18,  8, 24,  0, 48],
       [32, 16, 49,  9, 18],
       [25, 13, 13, 41,  5],
       [ 0, 12, 31, 24, 18]])

In [40]:
second_arr.reshape(2, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [42]:
second_arr.max()

19

In [43]:
second_arr.min()

0

In [46]:
second_arr.argmax()

19

In [49]:
rand_arr.max()

49

In [50]:
rand_arr.argmax()

7

In [52]:
rand_arr.argmin()

3

In [54]:
second_arr.shape

(20,)

In [55]:
reshaped_arr = second_arr.reshape(2, 10)

In [56]:
reshaped_arr.shape

(2, 10)

In [57]:
reshaped_arr.dtype

dtype('int32')