In [2]:
import numpy as np

In [3]:
int_arr = np.random.randint(0, 10, 10)

In [4]:
int_arr

array([5, 6, 8, 0, 6, 5, 1, 9, 6, 5])

In [6]:
int_arr[0]

5

In [7]:
int_arr[9]

5

In [8]:
int_arr[1:3]

array([6, 8])

In [9]:
int_arr[1:7]

array([6, 8, 0, 6, 5, 1])

In [10]:
int_arr[0:4]

array([5, 6, 8, 0])

In [11]:
int_arr[:4]

array([5, 6, 8, 0])

In [13]:
int_arr[4:10]

array([6, 5, 1, 9, 6, 5])

In [14]:
int_arr[4:]

array([6, 5, 1, 9, 6, 5])

In [15]:
int_arr[4:] = 10

In [16]:
int_arr

array([ 5,  6,  8,  0, 10, 10, 10, 10, 10, 10])

In [19]:
arr = np.arange(10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
new_arr = arr[:4]

In [22]:
new_arr

array([0, 1, 2, 3])

In [23]:
new_arr[2:] = 7

In [24]:
new_arr

array([0, 1, 7, 7])

In [25]:
arr

array([0, 1, 7, 7, 4, 5, 6, 7, 8, 9])

In [26]:
arr = np.arange(10)

In [27]:
new_arr = arr.copy()

In [28]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
new_arr[:] = 0

In [30]:
new_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [33]:
bool_arr = arr > 6

In [34]:
bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [35]:
arr[bool_arr]

array([7, 8, 9])

In [36]:
bool_arr = arr > 0

In [37]:
arr[bool_arr]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr[arr > 0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[arr < 5]

array([0, 1, 2, 3, 4])