In [1]:
import numpy as np

In [2]:
two_dim_arr = np.arange(12).reshape(3, 4)

In [4]:
two_dim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
two_dim_arr[1][1]

5

In [8]:
two_dim_arr[1, 1]

5

In [6]:
two_dim_arr[2][1]

9

In [9]:
two_dim_arr[2, 1]

9

In [10]:
two_dim_arr[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [11]:
two_dim_arr[:2, :2]

array([[0, 1],
       [4, 5]])

In [12]:
two_dim_arr[:2, 2:]

array([[2, 3],
       [6, 7]])

In [13]:
two_dim_arr[two_dim_arr > 4]

array([ 5,  6,  7,  8,  9, 10, 11])